language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc clang
    before_install:
    - sudo apt-get update -qq -y
    - sudo apt-get install libjansson-dev libsdl2-dev
  - os: osx
    compiler: clang
    before_install:
    - brew update
    - brew install jansson
    - brew install sdl2

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: cmake --build .
